import Head from 'next/head'
import styles from '../styles/about.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className={styles.text}>

        <div className={styles.title}>About Me</div>

        <div className={styles.me}>
          <div className={styles.subtitle}>Hi, I'm Im</div>
          <div className={styles.description}>
          My full name is Sadudee Theparree, I’m 16 years old and I am currently studying at the English Program 
          at Suankularb Wittayalai School in Mathayom 4. <br />
          I’m a big fan of puzzles and videogames and I didn’t 
          know I wanted to learn programming and do a lot more of it until only recently. <p />
          This website represents a progress bar of my journey in the development world, and it’ll be constantly updated to show the skills 
          and achievements I’ve learnt and gathered moving forward  over time.
          </div>
        </div>

        <div className={styles.programming}>
          <div className={styles["subtitle", "subtitle2"]}>Programming</div>
          <div className={styles.description}>
          It’s not been long since I first picked up programming, which was only a bit more than about half a year ago.
          Sure, there has been some programming that is required to be learnt by students in the curriculum, but in all honesty, they don’t really teach you much. <p />
          However, since around the end of last year, me and some of my friends have been taking programming courses non stop. As of the time of writing this, I’ve finished Harvard’s CS50w web development course and am now currently taking their CS50x course which is about computer science. Me and my friend specifically chose this course since our interest in A.I. and Machine Learning have peaked recently.
          </div>
        </div>

      </div>

    </div>
  )
}
