import Head from 'next/head'
import styles from '../styles/contacts.module.css'

export default function Contacts() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contacts</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className={styles.contents}>
        <div className={styles.title}>Contacts Page</div>

        <div className={styles.card}>

          <div className={styles.left_side}>
            <div className={styles.forms_container}>
              <form action="#" className={styles.forms}>
                <span>Full Name</span>
                <input type="text" name="full_name"></input>
                <span>E-Mail </span>
                <input type="text" name="email"></input>
                <span>Message </span>
                <textarea className={styles.message}></textarea>
              </form>
            </div>
            <button className={styles.send}></button>
          </div>

          <div className={styles.right_side}>
            <div className={styles.ty}>
              Thank You!
            </div>
            <div className={styles.icons}>
              <div className={styles.icon1}>
                picture and text goes here
              </div>
              <div className={styles.icon2}>
                picture and text goes here
              </div>
              <div className={styles.icon3}>
                picture and text goes here
              </div>
              <div className={styles.footer}>
                <div className={styles.contact}>
                  Contact
                  Sadudee.the@student.sk.ac.th
                </div>
                <div className={styles.base}>
                  Based In
                  Bangkok, Thailand
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  )
}
