import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import profile from '../public/profile.svg'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className={styles.scroller}></div>
      <div className={styles.title_container}>
        <span className={styles.greetings}>Hi, I&apos;m Im</span>
        <div className={styles.description}>Full Stack Developer</div>
        <button className={styles.contact_button}><Link href="/contacts"><a>Contact Me</a></Link></button>
      </div>
      <div className={styles.picture}>
        <Image className={styles.profile} src={profile} alt="Picture of me" />
      </div>
    </div>
  )
}
