import Head from 'next/head'
import styles from '../styles/skills.module.css'
import { useState } from 'react'
import Image from 'next/image'

import js from '../public/js.png'
import django from '../public/django.png'

export default function Skills() {
    // const mySkills = ["javascript", "django", "css", "python", "c", "c++", "c#", "java", "php"]
    const [skills, setSkills] = useState("js");


  return (
    <div className={styles.container}>
      <Head>
        <title>Skills</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className={styles.text}>
        <div className={styles.title}>Skills</div>

        <div className={styles.skills_container}>
          <table className={styles.skills}>
            <tr className={styles.js} onClick={()=> setSkills("js")}>
              <td className={styles.name}>Javascript</td>
              <td className={styles.level}>5</td>
            </tr>
            <tr className={styles.django} onClick={()=> setSkills("django")}>
              <td className={styles.name}>Django</td>
              <td className={styles.level}>4</td>
            </tr>
            <tr className={styles.css}>
              <td className={styles.name}>CSS</td>
              <td className={styles.level}>5</td>
            </tr>
            <tr className={styles.python}>
              <td className={styles.name}>Python</td>
              <td className={styles.level}>3</td>
            </tr>
            <tr className={styles.c}>
              <td className={styles.name}>C</td>
              <td className={styles.level}>2</td>
            </tr>
            <tr className={styles.c++}>
              <td className={styles.name}>C++</td>
              <td className={styles.level}>0</td>
            </tr>
            <tr className={styles.csharp}>
              <td className={styles.name}>C#</td>
              <td className={styles.level}>0</td>
            </tr>
            <tr className={styles.java}>
              <td className={styles.name}>Java</td>
              <td className={styles.level}>0</td>
            </tr>
            <tr className={styles.c}>
              <td className={styles.name}>php</td>
              <td className={styles.level}>0</td>
            </tr>
            <tr className={styles.scratch}>
              <td className={styles.name}>scratch</td>
              <td className={styles.level}>3</td>
            </tr>
          </table>
        </div>
      </div>

      <div className={styles.contents}>
          {skills === "js" && 
            <div className={styles.description_container}>
              <Image src={js} className={styles.jsImage} />
              <div className={styles.description}>
                descriptions about this programming language
              </div>
            </div>}
        </div>

    </div>
  )
}
